### ISSUE TITLE
Select list for changing groups is not populated

### ISSUE THREAD

**Issue by arnels** [itkinside/ufs#4]
Users aren't able to change between groups using the select list in the footer. The list is simply not populated.

![2019-10-29-235137_3840x1200_scrot](https://user-images.githubusercontent.com/5394881/67815639-c5693680-faa7-11e9-97fc-dc056f17e920.png)

**Comment by jodal** [comment]
Fixed by commit d2e68e4fc1281526d384cc585a8dd32c56ecfb32.
